{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[INFO] Installing jupyter-dash...\n",
            "[INFO] Installing dash-bootstrap-components...\n",
            "[INFO] Streaming PGN and collecting unique users...\n",
            "[INFO] 100000 games processed, 56506 unique users collected...\n",
            "[INFO] 200000 games processed, 93290 unique users collected...\n"
          ]
        }
      ],
      "source": [
        "# ======================================================\n",
        "# Lichess + FIDE Ratings Analysis + Interactive Dashboard\n",
        "# ======================================================\n",
        "\n",
        "# ======================================================\n",
        "# DEPENDENCY CHECK & INSTALL\n",
        "# ======================================================\n",
        "import importlib, subprocess, sys\n",
        "\n",
        "def install_if_missing(package_name):\n",
        "    if importlib.util.find_spec(package_name) is None:\n",
        "        print(f\"[INFO] Installing {package_name}...\")\n",
        "        subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", package_name])\n",
        "\n",
        "# Dashboard libraries\n",
        "install_if_missing(\"jupyter-dash\")\n",
        "install_if_missing(\"dash-bootstrap-components\")\n",
        "install_if_missing(\"plotly\")\n",
        "\n",
        "# Core libraries\n",
        "install_if_missing(\"chess\")\n",
        "install_if_missing(\"zstandard\")\n",
        "install_if_missing(\"pandas\")\n",
        "install_if_missing(\"seaborn\")\n",
        "install_if_missing(\"matplotlib\")\n",
        "install_if_missing(\"numpy\")\n",
        "install_if_missing(\"scipy\")\n",
        "install_if_missing(\"requests\")\n",
        "\n",
        "# ======================================================\n",
        "# IMPORTS\n",
        "# ======================================================\n",
        "import requests\n",
        "import zstandard as zstd\n",
        "import chess.pgn\n",
        "from io import TextIOWrapper\n",
        "import pandas as pd\n",
        "import seaborn as sns\n",
        "import matplotlib.pyplot as plt\n",
        "import os\n",
        "import numpy as np\n",
        "import zipfile\n",
        "import matplotlib.ticker as mticker\n",
        "from scipy.stats import pearsonr, linregress, t\n",
        "from IPython.display import Image, display\n",
        "\n",
        "# Dashboard imports\n",
        "from jupyter_dash import JupyterDash\n",
        "from dash import dcc, html, Input, Output\n",
        "import dash_bootstrap_components as dbc\n",
        "import plotly.graph_objects as go\n",
        "\n",
        "# ======================================================\n",
        "# PARAMETERS\n",
        "# ======================================================\n",
        "ZST_URL = \"https://database.lichess.org/standard/lichess_db_standard_rated_2025-09.pgn.zst\"\n",
        "TARGET_GAMES = 321654\n",
        "TARGET_UNIQUE_USERS = 123456\n",
        "EXPORT_DIR = \"lichess_ratings_by_timecontrol\"\n",
        "FIDE_ZIP_URL = \"http://ratings.fide.com/download/players_list.zip\"\n",
        "FIDE_DIR = \"fide_data_limited\"\n",
        "PLOT_DIR = \"plots\"\n",
        "os.makedirs(EXPORT_DIR, exist_ok=True)\n",
        "os.makedirs(FIDE_DIR, exist_ok=True)\n",
        "os.makedirs(PLOT_DIR, exist_ok=True)\n",
        "\n",
        "percentiles = np.linspace(0.01, 1.0, 100)\n",
        "time_control_labels = [\"bullet\", \"blitz\", \"rapid\", \"classical\"]\n",
        "\n",
        "# ======================================================\n",
        "# UTILITY FUNCTIONS\n",
        "# ======================================================\n",
        "#AI‑Assisted Code Note: Portions of the data‑ingestion logic and dashboard layout were developed/optimized \n",
        "# using suggestions from ChatGPT (e.g., library choice, streaming strategy). \n",
        "# These suggestions were reviewed and customised by me\n",
        "\n",
        "def classify_time_control(tc):\n",
        "    try:\n",
        "        if \"+\" in tc:\n",
        "            base, inc = tc.split(\"+\")\n",
        "            base = int(base)\n",
        "        else:\n",
        "            base = int(tc)\n",
        "        if base < 180:       return \"bullet\"\n",
        "        elif base < 600:     return \"blitz\"\n",
        "        elif base < 1800:    return \"rapid\"\n",
        "        else:                return \"classical\"\n",
        "    except:\n",
        "        return None\n",
        "\n",
        "def compute_percentiles(df, labels, percentiles):\n",
        "    data = []\n",
        "    for tc in labels:\n",
        "        subset = df[df[\"time_control\"] == tc][\"rating\"]\n",
        "        if subset.empty: continue\n",
        "        pct_values = np.percentile(subset, [p * 100 for p in percentiles])\n",
        "        data.append(pd.DataFrame({\n",
        "            \"time_control\": tc,\n",
        "            \"percentile\": percentiles,\n",
        "            \"rating\": pct_values\n",
        "        }))\n",
        "    return pd.concat(data, ignore_index=True)\n",
        "\n",
        "def save_plot(fig, name):\n",
        "    path = os.path.join(PLOT_DIR, name)\n",
        "    fig.savefig(path, bbox_inches='tight')\n",
        "    display(Image(path))\n",
        "\n",
        "def bootstrap_median_ci(data, n_boot=1000, ci=0.95):\n",
        "    medians = []\n",
        "    for _ in range(n_boot):\n",
        "        sample = np.random.choice(data, size=len(data), replace=True)\n",
        "        medians.append(np.median(sample))\n",
        "    lower = np.percentile(medians, (1-ci)/2*100)\n",
        "    upper = np.percentile(medians, (1+ci)/2*100)\n",
        "    return lower, upper\n",
        "\n",
        "def mean_ci(data, confidence=0.95):\n",
        "    n = len(data)\n",
        "    mean_val = np.mean(data)\n",
        "    std_err = np.std(data, ddof=1) / np.sqrt(n)\n",
        "    h = std_err * t.ppf((1 + confidence) / 2, n-1)\n",
        "    return mean_val - h, mean_val + h\n",
        "\n",
        "# ======================================================\n",
        "# STREAM LICHESS PGN\n",
        "# ======================================================\n",
        "print(\"[INFO] Streaming PGN and collecting unique users...\")\n",
        "unique_users = {}\n",
        "\n",
        "with requests.get(ZST_URL, stream=True) as r:\n",
        "    r.raise_for_status()\n",
        "    dctx = zstd.ZstdDecompressor()\n",
        "    with dctx.stream_reader(r.raw) as reader:\n",
        "        text_stream = TextIOWrapper(reader, encoding='utf-8', errors='ignore')\n",
        "        game_count = 0\n",
        "        for _ in range(TARGET_GAMES):\n",
        "            game = chess.pgn.read_game(text_stream)\n",
        "            if game is None:\n",
        "                break\n",
        "            h = game.headers\n",
        "            white, black = h.get(\"White\", \"\"), h.get(\"Black\", \"\")\n",
        "            try:\n",
        "                wr, br = int(h.get(\"WhiteElo\", 0)), int(h.get(\"BlackElo\", 0))\n",
        "            except:\n",
        "                continue\n",
        "            if not (white and black and wr and br):\n",
        "                continue\n",
        "            tc_category = classify_time_control(h.get(\"TimeControl\", \"\"))\n",
        "            if tc_category is None:\n",
        "                continue\n",
        "            if white not in unique_users and len(unique_users) < TARGET_UNIQUE_USERS:\n",
        "                unique_users[white] = {\"rating\": wr, \"time_control\": tc_category}\n",
        "            if black not in unique_users and len(unique_users) < TARGET_UNIQUE_USERS:\n",
        "                unique_users[black] = {\"rating\": br, \"time_control\": tc_category}\n",
        "            game_count += 1\n",
        "            if game_count % 100_000 == 0:\n",
        "                print(f\"[INFO] {game_count} games processed, {len(unique_users)} unique users collected...\")\n",
        "            if len(unique_users) >= TARGET_UNIQUE_USERS:\n",
        "                print(\"[INFO] Target unique users reached.\")\n",
        "                break\n",
        "\n",
        "print(f\"[INFO] Finished. Games processed: {game_count}, Unique users collected: {len(unique_users)}\")\n",
        "\n",
        "df_users = pd.DataFrame([{\"player\": u, \"rating\": d[\"rating\"], \"time_control\": d[\"time_control\"]}\n",
        "                         for u, d in unique_users.items()])\n",
        "\n",
        "# ======================================================\n",
        "# LICHESS EDA & SAVE PLOTS\n",
        "# ======================================================\n",
        "sns.set(style=\"whitegrid\", context=\"talk\")\n",
        "\n",
        "# Histograms\n",
        "plt.figure(figsize=(14, 8))\n",
        "for i, tc in enumerate(time_control_labels):\n",
        "    subset = df_users[df_users[\"time_control\"] == tc]\n",
        "    if subset.empty: continue\n",
        "    plt.subplot(2, 2, i + 1)\n",
        "    sns.histplot(subset[\"rating\"], bins=40, kde=True, color=\"skyblue\", edgecolor=\"black\")\n",
        "    plt.title(f\"{tc.capitalize()} Rating Distribution (Lichess)\")\n",
        "    plt.xlabel(\"Rating (Elo)\")\n",
        "    plt.ylabel(\"Number of Players\")\n",
        "plt.tight_layout()\n",
        "save_plot(plt, \"lichess_histograms.png\")\n",
        "plt.close()\n",
        "\n",
        "# Boxplot\n",
        "plt.figure(figsize=(10, 6))\n",
        "sns.boxplot(x=\"time_control\", y=\"rating\", data=df_users, palette=\"Pastel2\")\n",
        "plt.title(\"Boxplot of Lichess Ratings by Time Control\")\n",
        "plt.xlabel(\"Time Control\")\n",
        "plt.ylabel(\"Rating (Elo)\")\n",
        "plt.grid(True, alpha=0.3)\n",
        "save_plot(plt, \"lichess_boxplot.png\")\n",
        "plt.close()\n",
        "\n",
        "# ======================================================\n",
        "# SUMMARY STATISTICS (NEW)\n",
        "# ======================================================\n",
        "summary_stats = []\n",
        "\n",
        "for tc in time_control_labels:\n",
        "    subset = df_users[df_users[\"time_control\"] == tc][\"rating\"]\n",
        "    if subset.empty: continue\n",
        "    mean_val = subset.mean()\n",
        "    median_val = subset.median()\n",
        "    std_val = subset.std()\n",
        "    mean_lower, mean_upper = mean_ci(subset)\n",
        "    med_lower, med_upper = bootstrap_median_ci(subset)\n",
        "    \n",
        "    summary_stats.append({\n",
        "        \"time_control\": tc,\n",
        "        \"mean\": mean_val,\n",
        "        \"median\": median_val,\n",
        "        \"std\": std_val,\n",
        "        \"mean_95_CI\": (mean_lower, mean_upper),\n",
        "        \"median_95_CI\": (med_lower, med_upper)\n",
        "    })\n",
        "\n",
        "summary_df = pd.DataFrame(summary_stats)\n",
        "display(summary_df)\n",
        "\n",
        "# ======================================================\n",
        "# FIDE RATINGS\n",
        "# ======================================================\n",
        "print(\"[INFO] Downloading and extracting limited FIDE rating list...\")\n",
        "fide_zip_path = os.path.join(FIDE_DIR, \"players_list.zip\")\n",
        "r = requests.get(FIDE_ZIP_URL)\n",
        "with open(fide_zip_path, \"wb\") as f:\n",
        "    f.write(r.content)\n",
        "\n",
        "with zipfile.ZipFile(fide_zip_path, \"r\") as zip_ref:\n",
        "    zip_ref.extractall(FIDE_DIR)\n",
        "\n",
        "fide_file = next((os.path.join(FIDE_DIR, f) for f in os.listdir(FIDE_DIR) if f.lower().endswith(\".txt\")), None)\n",
        "if fide_file is None:\n",
        "    raise FileNotFoundError(\"No FIDE player list file found!\")\n",
        "\n",
        "fide_df = pd.read_fwf(fide_file, nrows=150_000, encoding=\"latin-1\")\n",
        "fide_df.columns = [c.strip().lower() for c in fide_df.columns]\n",
        "rating_cols = [c for c in fide_df.columns if \"rtng\" in c.lower()]\n",
        "rating_df = fide_df[rating_cols].apply(pd.to_numeric, errors=\"coerce\")\n",
        "\n",
        "rename_map = {}\n",
        "for c in rating_df.columns:\n",
        "    name = c.lower()\n",
        "    if \"rapid\" in name or \"rr\" in name:\n",
        "        rename_map[c] = \"Rapid\"\n",
        "    elif \"blitz\" in name or \"br\" in name:\n",
        "        rename_map[c] = \"Blitz\"\n",
        "    elif \"std\" in name or \"rtng\" in name:\n",
        "        rename_map[c] = \"Standard\"\n",
        "    else:\n",
        "        rename_map[c] = c\n",
        "\n",
        "rating_df = rating_df.rename(columns=rename_map)\n",
        "fide_ratings = rating_df.melt(var_name=\"time_control\", value_name=\"rating\").dropna()\n",
        "fide_ratings = fide_ratings[fide_ratings[\"rating\"] > 0]\n",
        "\n",
        "# Histograms\n",
        "plt.figure(figsize=(12, 6))\n",
        "sns.histplot(data=fide_ratings, x=\"rating\", hue=\"time_control\", bins=60, kde=True)\n",
        "plt.title(\"FIDE Rating Distributions (Standard / Rapid / Blitz)\")\n",
        "plt.xlabel(\"FIDE Rating\")\n",
        "plt.ylabel(\"Number of Players\")\n",
        "plt.grid(True, alpha=0.3)\n",
        "save_plot(plt, \"fide_histograms.png\")\n",
        "plt.close()\n",
        "\n",
        "# Boxplot\n",
        "plt.figure(figsize=(10, 6))\n",
        "sns.boxplot(x=\"time_control\", y=\"rating\", data=fide_ratings, palette=\"Pastel1\")\n",
        "plt.title(\"Boxplot of FIDE Ratings by Time Control\")\n",
        "plt.xlabel(\"Time Control\")\n",
        "plt.ylabel(\"Rating (Elo)\")\n",
        "plt.grid(True, alpha=0.3)\n",
        "save_plot(plt, \"fide_boxplot.png\")\n",
        "plt.close()\n",
        "\n",
        "# ======================================================\n",
        "# COMPUTE PERCENTILES & MAPPING\n",
        "# ======================================================\n",
        "lichess_pct_df = compute_percentiles(df_users, time_control_labels, percentiles)\n",
        "fide_pct_df = compute_percentiles(fide_ratings, [\"Standard\", \"Rapid\", \"Blitz\"], percentiles)\n",
        "\n",
        "alignment = {\"bullet\": \"Blitz\", \"blitz\": \"Blitz\", \"rapid\": \"Rapid\", \"classical\": \"Standard\"}\n",
        "mapping_data = []\n",
        "\n",
        "for lichess_tc, fide_tc in alignment.items():\n",
        "    l_df = lichess_pct_df[lichess_pct_df[\"time_control\"] == lichess_tc]\n",
        "    f_df = fide_pct_df[fide_pct_df[\"time_control\"] == fide_tc]\n",
        "    if l_df.empty or f_df.empty:\n",
        "        continue\n",
        "    merged = pd.merge(l_df, f_df, on=\"percentile\", suffixes=(\"_lichess\", \"_fide\"))\n",
        "    merged[\"lichess_tc\"] = lichess_tc\n",
        "    merged[\"fide_tc\"] = fide_tc\n",
        "    mapping_data.append(merged)\n",
        "\n",
        "mapping_df = pd.concat(mapping_data, ignore_index=True)\n",
        "mapping_df.to_csv(\"lichess_fide_mapping_points.csv\", index=False)\n",
        "\n",
        "# Scatter + Trendline Plot for each time control (static)\n",
        "for tc in time_control_labels:\n",
        "    subset = mapping_df[mapping_df[\"lichess_tc\"] == tc]\n",
        "    if subset.empty:\n",
        "        continue\n",
        "    corr, _ = pearsonr(subset[\"rating_lichess\"], subset[\"rating_fide\"])\n",
        "    slope, intercept, _, _, _ = linregress(subset[\"rating_lichess\"], subset[\"rating_fide\"])\n",
        "    reg_line = slope * subset[\"rating_lichess\"] + intercept\n",
        "    plt.figure(figsize=(8, 6))\n",
        "    plt.scatter(subset[\"rating_lichess\"], subset[\"rating_fide\"], alpha=0.6, label=\"Data points\")\n",
        "    plt.plot(subset[\"rating_lichess\"], reg_line, color=\"red\", label=f\"Trendline (r={corr:.2f})\")\n",
        "    plt.title(f\"Lichess {tc.capitalize()} → FIDE {alignment[tc]} Mapping\")\n",
        "    plt.xlabel(\"Lichess Rating\")\n",
        "    plt.ylabel(\"FIDE Rating\")\n",
        "    plt.grid(True, alpha=0.3)\n",
        "    plt.legend()\n",
        "    save_plot(plt, f\"mapping_{tc}.png\")\n",
        "    plt.close()\n",
        "\n",
        "# ======================================================\n",
        "# JUPYTERDASH DASHBOARD (Dash 3 compliant)\n",
        "# ======================================================\n",
        "app = JupyterDash(__name__, external_stylesheets=[dbc.themes.SLATE])\n",
        "\n",
        "app.layout = dbc.Container([\n",
        "    html.H2(\"Lichess ↔ FIDE Ratings Interactive Dashboard\", className=\"text-center my-4\"),\n",
        "    dbc.Row([\n",
        "        dbc.Col([\n",
        "            html.Label(\"Select Time Control:\"),\n",
        "            dcc.Dropdown(\n",
        "                id=\"time_control_dropdown\",\n",
        "                options=[{\"label\": tc.capitalize(), \"value\": tc} for tc in time_control_labels],\n",
        "                value=\"blitz\",\n",
        "                clearable=False\n",
        "            )\n",
        "        ], width=4)\n",
        "    ], justify=\"center\"),\n",
        "    dcc.Graph(id=\"mapping_graph\", style={\"height\": \"600px\"}),\n",
        "    html.Div(id=\"summary_output\", className=\"text-center mt-4\", style={\"color\": \"white\"})\n",
        "], fluid=True)\n",
        "\n",
        "@app.callback(\n",
        "    [Output(\"mapping_graph\", \"figure\"),\n",
        "     Output(\"summary_output\", \"children\")],\n",
        "    [Input(\"time_control_dropdown\", \"value\")]\n",
        ")\n",
        "def update_dashboard(selected_tc):\n",
        "    subset = mapping_df[mapping_df[\"lichess_tc\"] == selected_tc]\n",
        "    if subset.empty:\n",
        "        fig = go.Figure()\n",
        "        fig.update_layout(title=f\"No data for {selected_tc}\")\n",
        "        return fig, f\"No data available for {selected_tc}.\"\n",
        "    corr, _ = pearsonr(subset[\"rating_lichess\"], subset[\"rating_fide\"])\n",
        "    slope, intercept, _, _, _ = linregress(subset[\"rating_lichess\"], subset[\"rating_fide\"])\n",
        "    reg_line = slope * subset[\"rating_lichess\"] + intercept\n",
        "    fig = go.Figure()\n",
        "    fig.add_trace(go.Scatter(\n",
        "        x=subset[\"rating_lichess\"], y=subset[\"rating_fide\"],\n",
        "        mode=\"markers\", name=\"Data points\", opacity=0.6\n",
        "    ))\n",
        "    fig.add_trace(go.Scatter(\n",
        "        x=subset[\"rating_lichess\"], y=reg_line,\n",
        "        mode=\"lines\", name=f\"Trendline (r={corr:.2f})\", line=dict(color=\"red\")\n",
        "    ))\n",
        "    fig.update_layout(\n",
        "        title=f\"Lichess {selected_tc.capitalize()} → FIDE {alignment[selected_tc]} Mapping\",\n",
        "        xaxis_title=\"Lichess Rating\",\n",
        "        yaxis_title=\"FIDE-Equivalent Rating\",\n",
        "        template=\"plotly_dark\",\n",
        "        xaxis=dict(tick0=0, dtick=200),\n",
        "        yaxis=dict(tick0=0, dtick=200),\n",
        "    )\n",
        "    summary = f\"Correlation (r): {corr:.3f} | Regression slope: {slope:.3f} | Intercept: {intercept:.1f}\"\n",
        "    return fig, summary\n",
        "\n",
        "# ======================================================\n",
        "# RUN DASHBOARD LOCALLY IN NOTEBOOK\n",
        "# ======================================================\n",
        "app.run(mode=\"inline\", debug=True)"
      ]
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "name": "Data Practitioner Jupyter Notebook.ipynb",
      "provenance": [],
      "toc_visible": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.12.8"
    },
    "orig_nbformat": 2
  },
  "nbformat": 4,
  "nbformat_minor": 2
}
